CREATE TABLE federal_subjects (
  FS_ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  FS_name VARCHAR(255) NOT NULL -- fedSubjName
);
CREATE TABLE locations (
  LOC_ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  LOC_name VARCHAR(255) NOT NULL, -- locationName
  LOC_FS_ID INTEGER NOT NULL -- ссылка на federal_subjects.FS_ID
);
CREATE TABLE cert_issuers (
  CI_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  CI_name VARCHAR(255) NOT NULL -- certIssuerName
);
CREATE TABLE sources (
  SOUR_ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  SOUR_SOUR_ID INTEGER, -- ссылка на sources.SOUR_ID
  SOUR_name VARCHAR(25) NOT NULL, -- sourceName
  SOUR_fullName VARCHAR(255) NOT NULL, -- sourceFullName
  SOUR_CI_ID INTEGER NOT NULL, -- ссылка на cert_issuers.CI_ID
  SOUR_LOC_ID INTEGER NOT NULL, -- ссылка на locations.LOC_ID
  SOUR_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  SOUR_insDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE cert (
  CERT_ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  CERT_EXAM_ID INTEGER NOT NULL, -- ссылка на exam.EXAM_ID
  CERT_date DATE, -- cDate 4 байта
  CERT_regno INTEGER, -- regno
  CERT_insDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE cert_sources ( -- PK: CRSR_CERT_ID, CRSR_SOUR_ID, CRSR_date представляется неправильным выдача сертификата и его дубликата( или двух дубликатов ) в один день
  CRSR_CERT_ID INTEGER NOT NULL, -- ссылка на cert.CERT_ID
  CRSR_SOUR_ID INTEGER NOT NULL, -- ссылка на sources.SOUR_ID
-- сдается, что в такой конструкции табличка session вообще не нужна???  CRSR_SESS_ID INTEGER, -- ссылка на session.SESS_ID
  CRSR_duplicate BOOLEAN NOT NULL DEFAULT FALSE,
  CRSR_date DATE NOT NULL -- думаю здесь хранить дату выдачи сертификатов и дубликатов и тогда наверно cert.CERT_date не нужно
);
